<!-- BEGIN TOUR -->
    <section id="tour1">
        <div class="tour-top bg-blue">
            <div class="banner-container">
                <div class="banner">
                    <ul>
                        <!-- SLIDE  -->
                        <li data-transition="fade">
                            <!-- MAIN IMAGE -->
                            <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/tour/tour_bg.png" alt="tour">
                            <!-- LAYERS -->
                            <div class="caption sft" data-x="300" data-y="125" data-speed="600" data-start="500" data-endspeed="600" data-endeasing="easeIn" style="z-index: 3;">
                                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/mockup_laptop_front.png" alt="laptop">
                            </div>
                            <div class="caption sfb" data-x="140" data-y="210" data-speed="800" data-start="1200" data-endspeed="300" data-endeasing="easeIn" data-captionhidden="off" style="z-index: 4;">
                                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/mockup_ipad.png" alt="ipad">
                            </div>
                            <div class="caption sfr" data-x="615" data-y="300" data-speed="800" data-start="1500" data-endspeed="300" data-endeasing="easeIn" data-captionhidden="off" style="z-index: 4;">
                                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/mockup_phone.png" alt="phone">
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="tour-title bg-white">
            <h1>The perfect App landing page</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit integer nibh risus hendrerit eget sem ut, tempor condimentum felis.
             </p>
                <a href="#" class="btn btn-blue btn-lg  btn-large">BUY IT NOW</a>
                <br>
                <br>
                <a id="tour1_next" class="control-btn go-down fa fa-chevron-down" href="#"></a>
           
        </div>
    </section>
    <section class="tour-section bg-white animated-section" id="tour2">
        <div class="row side top">
            <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
                <h1>Buildt with Bootstrap v3.1</h1>
                <p>Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum.
                </p>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <i class="glyph-icon flaticon-widgets fa-5x m-b-20"></i>
                <h3>Fully Responsive</h3>
                <p>Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum.
                </p>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <i class="glyph-icon flaticon-html9 fa-5x m-b-20"></i>
                <h3>HTML5 &amp; CSS3</h3>
                <p>Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum.
                </p>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <i class="glyph-icon flaticon-tools6 fa-5x m-b-20"></i>
                <h3>Many Icons</h3>
                <p>Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum.
                </p>
            </div>
            <div class="col-lg-12">
                <div class="appear" id='svg-animated'></div>
            </div>
        </div>
    </section>
    <section class="arrows_box">
        <div class="arrows">
            <div id="tour2_next" class="go-down">
                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/arrow_down.png" alt="">
            </div>
            <div id="tour2_back" class="go-up">
                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/arrow_up.png" alt="">
            </div>
        </div>
    </section>
    <section class="tour-section animated-section" id="tour3">
        <div class="row">
            <article class="side left col-sm-6">
                <h1>Fully Responsive</h1>
                <p>Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum.</p>
                <div>
                    <div class="feature">
                        <h4><i class="fa fa-desktop"></i> Beautiful, modern design</h4>
                        <p>Epsum factorial non deposit quid pro quo
                            <br>hic escorol.</p>
                    </div>
                    <div class="feature">
                        <h4><i class="fa fa-check"></i> Easy to implement</h4>
                        <p>Epsum factorial non deposit quid pro quo
                            <br>hic escorol.</p>
                    </div>
                </div>
            </article>
            <figure class="side side-img right col-sm-6">
                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/mockup_right.png" alt="inbox page" class="img-responsive">
            </figure>
        </div>
    </section>
    <section class="arrows_box">
        <div class="arrows">
            <div id="tour3_next" class="go-down">
                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/arrow_down.png" alt="">
            </div>
            <div id="tour3_back" class="go-up">
                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/arrow_up.png" alt="">
            </div>
        </div>
    </section>
    <section class="tour-section animated-section bg-white" id="tour4">
        <div class="row">
            <figure class="side side-img left col-sm-6">
                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/mockup_left.png" alt="homepage" class="img-responsive">
            </figure>
            <article class="side right col-sm-6">
                <h1>HTML5 &amp; CSS3</h1>
                <p>Lollipop powder danish sugar plum caramels liquorice sweet cookie. Gummi bears caramels gummi bears candy canes cheesecake sweet roll icing dragée. Gummies jelly-o tart. Cheesecake unerdwear.com candy canes apple pie halvah chocolate tiramisu.</p>
                <div>
                    <div class="feature">
                        <h4><i class="fa fa-desktop"></i> Beautiful, modern design</h4>
                        <p>Epsum factorial non deposit quid pro quo
                            <br>hic escorol.
                        </p>
                    </div>
                    <div class="feature">
                        <h4><i class="fa fa-check"></i> Easy to implement</h4>
                        <p>Epsum factorial non deposit quid pro quo
                            <br>hic escorol.
                        </p>
                    </div>
                </div>
            </article>
        </div>
    </section>
    <section class="arrows_box">
        <div class="arrows arrows-last">
            <div id="tour_back_to_top" class="go-up">
                <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/arrow_up.png" alt="">
            </div>
        </div>
    </section>
    <!-- END TOUR -->
    <!-- BEGIN TESTIMONIALS -->
    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="span12 p-t-50 p-b-40">
                    <div id="testimonials" class="owl-carousel">
                        <div class="item">
                            <div class="col-md-6  col-md-offset-3">
                                <h3 class="normal text-center">
                                    I have been very impressed with your friendliness and responsiveness. Thank you so much and I'm waiting for the next theme!
                                </h3>
                                <p class="text-center">
                                    <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/testimonial1.jpg" class="img-circle" alt="Testimonial 1">Steve Mac Queen, client, New York City
                                </p>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-6  col-md-offset-3">
                                <h3 class="normal text-center">
                                    I have been very impressed with your friendliness and responsiveness. Thank you so much and I'm waiting for the next theme!
                                </h3>
                                <p class="text-center">
                                    <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/testimonial2.jpg" class="img-circle" alt="Testimonial 2">Steve Mac Queen, client, New York City
                                </p>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-6  col-md-offset-3">
                                <h3 class="normal text-center">
                                    I have been very impressed with your friendliness and responsiveness. Thank you so much and I'm waiting for the next theme!
                                </h3>
                                <p class="text-center">
                                    <img src="<?=$this->layout()->layout["SITE_URL"]?>/assetsfront/img/testimonial3.jpg" class="img-circle" alt="Testimonial 3">Steve Mac Queen, client, New York City
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END TESTIMONIALS -->